tables:
  sitenews:
    field:
      id:
        primary_key: true
        type: varchar(50)
        not_null: true
      date:
        type: date
      headline:
        type: varchar(255)
      description:
        type: text
      description_more:
        type: text
extra:
  _description: Extra field to add to each table if not exist in schema.
  field:
    created_at:
      type: timestamp
      default: CURRENT_TIMESTAMP
    updated_at:
      type: timestamp
    created_by:
      type: varchar(50)
    updated_by:
      type: varchar(50)
      
        
        
        
        